name: Node.js CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '14.x', ]

    name: Node ${{ matrix.node }} sample

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          make install
        env:
          CI: true

      - name: Run linter
        run: |
          make lint
